### ISSUE TITLE
fix(go): constraint error (1.13.0): improper constraint

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#1011]
## Error
We have a warning in go scanning.

```
2021-05-20T14:21:01.319Z	WARN	constraint error (1.13.0): improper constraint: 
```

https://github.com/aquasecurity/trivy/runs/2630920793

**Comment by knqyf263** [comment]
@rahul2393 Could you look into it?

**Comment by rahul2393** [comment]
This happens because of this vulnerability
https://github.com/aquasecurity/vuln-list/blob/main/glad/go/k8s.io/kubernetes/CVE-2020-8554.json, FixedVersion is empty.
<img width="666" alt="Screenshot 2021-05-23 at 2 52 25 PM" src="https://user-images.githubusercontent.com/18293335/119254897-8002e180-bbd6-11eb-85db-694ccd719627.png">

**Comment by knqyf263** [comment]
Thanks. If a fixed version is empty, we should detect it anyway. Could you open a PR?
