### ISSUE TITLE
What is Jenkinsfile shell instruction for trivy cli to generate HTML report?

### ISSUE THREAD

**Issue by sourabhgupta385** [aquasecurity/trivy#1171]
I want to execute below command in Jenkins
trivy image --format template --template "@contrib/html.tpl" -o trivy-report.html --input helloworld_${BUILD_NUMBER}.tar

In above command note double quotes with @

In Jenkinsfile, I have given instruction as :

sh script: 'trivy --cache-dir /tmp/trivy image --format template --template \"@contrib/html.tpl\" -o trivy-report.html --input helloworld_${BUILD_NUMBER}.tar'

but in jenkins logs I see:

[Pipeline] sh

trivy --cache-dir /tmp/trivy image --format template --template @contrib/html.tpl -o trivy-report.html --input helloworld__44.tar

i.e. because of @ just after double quotes, double quotes is omitted. For the command double quotes and @ needs to be adjacent for it to run properly. Can anyone please help me with this? I've tried a lot of options but nothing works.

**Comment by savujevi** [comment]
Hello,
I don't know if it helps, but this works for me:

def String trivyStatus = sh returnStatus: true, script: """trivy -q image --severity "HIGH,CRITICAL" --ignorefile /tmp/.trivyignore --exit-code 1 --ignore-unfixed --format template --template "@/tmp/html.tpl" -o /tmp/report.html YOUR_IMAGE"""

**Comment by savujevi** [comment]
But I use trivy installed in a own slave.

**Comment by caiohasouza** [comment]
Hi,

I use this sh step:

> sh """
  cd /
  trivy image --vuln-type os --no-progress --format template --template @contrib/html.tpl -o ${WORKSPACE}/trivy-reports/${DOCKER_IMAGE}-OS.html ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}/${DOCKER_IMAGE}:${BUILD_NUMBER}
"""

The main point is the "cd /", it's because jenkins-slave start container on workspace directory, but the file "@contrib/html.tpl" is at /.

I hope that help you.
