### ISSUE TITLE
--download-db-only for trivy config

### ISSUE THREAD

**Issue by jzr1991** [aquasecurity/trivy#1301]
Could we replicate this feature/behaviour from "trivy image" where you can use --download-db-only to install the db/files for vuln scanning up front, but for "trivy config" when wanting to check for misconfigurations.

If gchr is down/unstable, or for offline usage, this would be useful.

Thanks!

**Comment by mzakarian** [comment]
I currently have the problem that, due to my network settings, I am unable to check for misconfigured files using trivy, as I cannot access **ghcr.io/aquasecurity/appshield** from my network as described here:

> Policy Distribution
https://aquasecurity.github.io/trivy/v0.21.1/misconfiguration/policy/builtin/#policy-distribution
AppShield policies are distributed as an OPA bundle on GitHub Container Registry (GHCR). When misconfiguration detection is enabled, Trivy pulls the OPA bundle from GHCR as an OCI artifact and stores it in the cache. Those policies are then loaded into Trivy OPA engine and used for detecting misconfigurations.

The configuration scan fails with the following prompt
```sh
2021-11-25T15:54:17.835Z	INFO	Need to update the built-in policies
2021-11-25T15:54:17.835Z	INFO	Downloading the built-in policies...
2021-11-25T15:54:17.969Z	FATAL	scan error: failed to initialize built-in policies: failed to download built-in policies: OPA bundle error: OCI repository error: Get "https://ghcr.io/v2/": Forbidden
```
I would like to see an air-gapped method for the configuration scan, similar to the image scan, where I can download and extract the built-in configurations beforehand from **aquasecurity/appshield** via a in-house mirror.
