### ISSUE TITLE
Integration with GitLab will stop working in GitLab 15.0

### ISSUE THREAD

**Issue by thiago-gitlab** [aquasecurity/trivy#1598]
[Container scanning schemas below 14.0.0](https://docs.gitlab.com/ee/update/deprecations#container-scanning-schemas-below-1400) have been deprecated.

[`blob/main/contrib/gitlab.tpl:3`](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab.tpl#L3) is using a deprecated version:

>   "version": "2.3",

The latest version of the schema is [14.1.0](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas/14.1.0). There are other [schemas available](https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee/lib/ee/gitlab/ci/parsers/security/validators/schemas); any version from 14.0.0 is supported.

From GitLab 15.0, any reports submitted using an unsupported version will be rejected.

**Comment by thiago-gitlab** [comment]
Note that the GitLab [container scanning](https://docs.gitlab.com/ee/user/application_security/container_scanning/) analyzer itself, which is a wrapper around Trivy, already uses the new schema. 

This is only for the `--template "@contrib/gitlab.tpl"` option, as described in https://github.com/aquasecurity/trivy/blob/main/docs/advanced/integrations/gitlab-ci.md.

**Comment by knqyf263** [comment]
Thanks for sharing! We will move to the new schema.

**Comment by thiago-gitlab** [comment]
Hi, @knqyf263. I have drummed this up in our team, and hope someone will volunteer to work on it. Otherwise I might give this one a crack myself.

**Comment by knqyf263** [comment]
We welcome any contribution from anyone 👍

**Comment by jfowl** [comment]
Isn't this just copying https://gitlab.com/gitlab-org/security-products/analyzers/container-scanning/-/blob/master/lib/template/trivy.tpl over to contrib?

**Comment by thiago-gitlab** [comment]
@jfowl not quite because the [GitLab analyzer adds/modifies some properties](https://gitlab.com/gitlab-org/security-products/analyzers/container-scanning/-/blob/a19f28c8500e50bc2ea0514576308262431556ae/lib/gcs/converter.rb#L13) that are not part of the template.

**Comment by jfowl** [comment]
Ah, I see. My brain fart had to be too good to be true.

**Comment by davinkevin** [comment]
I think there is more than just upgrading `contrib` from trivy, because the last version (`0.23.0`) doesn't allow to use embedded templates anymore:

![image](https://user-images.githubusercontent.com/1970922/152645874-1ef79c6f-8e3e-419d-aaa6-51c4edba45d2.png)

**Comment by knqyf263** [comment]
@davinkevin It works in my environment. Please make sure your template is in the path you specified.

**Comment by davinkevin** [comment]
I thought (from the beginning) templates where embedded in the binary 🤦 . So, testing it from my `brew` installation leads to this error while in CI is OK. Sorry for the bad comment.

PS: embedded template could be good rather than relying in location on file system (in brew context, I don't know where they are installed by default).

**Comment by thiago-gitlab** [comment]
@knqyf263 @krol3 GitLab is bringing container scanning to free on version 15.0: https://gitlab.com/groups/gitlab-org/-/epics/2233

While this integration will still break, Trivy users should be able to use the GitLab container scanning template instead. This can be an update to https://github.com/aquasecurity/trivy/blob/main/docs/advanced/integrations/gitlab-ci.md

From:
> If you're a GitLab Ultimate customer, GitLab 14.0 and above include out-of-the-box integration with Trivy. 

To:

> GitLab 15.0 and above include out-of-the-box integration with Trivy.

**Comment by krol3** [comment]
@thiago-gitlab great news! Could you help us with the documentation about Trivy and Gitlab?  to have this information in the oficial Trivy documentation too.

**Comment by thiago-gitlab** [comment]
@krol3 I'd be happy to provide an MR with the suggestion above.

There's already a link to https://docs.gitlab.com/ee/user/application_security/container_scanning/ from https://github.com/aquasecurity/trivy/blob/main/docs/advanced/integrations/gitlab-ci.md.

Do you think we should add anything else?

**Comment by thiago-gitlab** [comment]
So GitLab 15.0 came around, I didn't have time to contribute a fix, and this integration has broken as expected.

On a positive note, Container Scanning is now part of GitLab Core (free): https://gitlab.com/groups/gitlab-org/-/epics/2233

So all users should be able to use GitLab's own [Container Scanning CI configuration template](https://docs.gitlab.com/ee/user/application_security/container_scanning/#configuration):

```yaml
include:
  - template: Security/Container-Scanning.gitlab-ci.yml
```

My suggestion:
1. Remove the CI configuration from the Trivy repo
2. Update docs to teach users to use the snippet above, and perhaps point to GitLab's configuration page https://github.com/aquasecurity/trivy/blob/main/docs/docs/integrations/gitlab-ci.md

**Comment by thiago-gitlab** [comment]
@krol3, I've submitted a PR to update the docs here: https://github.com/aquasecurity/trivy/pull/2153.

I have opted to leave the current `contrib/gitlab.tpl` in place since it can benefit users of older versions of GitLab. I made a note to point-out that it doesn't work with GitLab 15.0.

Please let me know what you think.

**Comment by KGAJUL** [comment]
@thiago-gitlab  .. I am using Gitlab 15 version and when i moved to new version of trivy (latest image) under security tab i am not seeing report and getting below error,
[Schema] property '/version' does not match pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
[Schema] Version 2.3 for report type container_scanning is unsupported, supported versions for this report type are: 14.0.0, 14.0.1, 14.0.2, 14.0.3, 14.0.4, 14.0.5, 14.0.6, 14.1.0, 14.1.1, 14.1.2

Yes, i gone through your documentation. GitLab 15 won't support for "@/contrib/gitlab.tpl" instead asked to use for default container scanning ci. 

Just checking is there any way found that still i could fix and create json report using the same template ? or for gitlab 15 version only option is "Security/Container-Scanning.gitlab-ci.yml"

**Comment by thiago-gitlab** [comment]
Hi, @KGAJUL. 

Yes, these errors are expected as described in this issue.

In GitLab 15.0, the container scanning moved to free, and you could use that instead; see my previous comment: https://github.com/aquasecurity/trivy/issues/1598#issuecomment-1128585049.

Alternatively, if you're running a self-managed instance, you can use the `enforce_security_report_validation` feature flag until GitLab 15.3. After that, the [feature flag will be removed](https://gitlab.com/gitlab-org/gitlab/-/issues/355628) and ingestion will only work with reports that pass validation.

Please see [instructions on how to enable the feature flag](https://docs.gitlab.com/ee/administration/feature_flags.html).

**Comment by AljoschaP** [comment]
As far as I understand the docs and the discussion, without support for the new schema a lot of use cases will be impossible. For instance, if I want to check multiple images in a single job, create a merged report and use it in `artifacts` this is not possible. Is this correct?

**Comment by yuha0** [comment]
The gitlab official image scanning pipeline relies on docker and runs a docker-in-docker setup. This is convenient for folks who use docker, but I believe a lot of users have already replaced it with other container runtimes, or is in the progress to do so, since Kubernetes deprecated support for docker shim.

From security perspective, personally I am also not a fan of docker-in-docker and I don't feel comfortable exposing docker socket to a container, especially for a security tool like trivy. Technically, trivy does not need such privilege anyways.

**Comment by thiago-gitlab** [comment]
> Trivy seems to be agnostic to container runtimes as it can just scan an OCI tarball, it has been working just fine for us and I would love to keep using it in such way.

@yuha0, is there anything in this issue indicating that users can't keep using it this way?

**Comment by yuha0** [comment]
I think this issue is about trivy's existing template being incompatible with GitLab 15. I see that you had a PR to update that now. That can resolve this issue for me. Thank you!

I understand that GitLab has various executor types. But this security scanning feature you brought up [explicitly require docker](https://gitlab.com/gitlab-org/gitlab/-/blob/7a8b2243109dba91bc2fbcc8fb0ab626183685d6/doc/user/application_security/container_scanning/index.md#L75). And I know a lot of folks use other container runtimes (containerd, cri-o...etc) and can't setup a CI environment for docker.

**Comment by thiago-gitlab** [comment]
@yuha0, I'm happy to answer questions about Trivy integration with GitLab, but I don't want to continue an unrelated discussion about GitLab functionality on another company's forum.

If you have any questions or suggestions, I invite you to join https://forum.gitlab.com/, or read https://about.gitlab.com/submit-feedback/#product-feedback to learn other ways to provide product feedback. Thank you.

**Comment by yuha0** [comment]
Hi @thiago-gitlab 

One of your proposals above was to remove custom template from Trivy documentation and ask all users to use GitLab official pipeline, because "all users should be able to use GitLab's own [Container Scanning CI configuration template](https://docs.gitlab.com/ee/user/application_security/container_scanning/#configuration)". 

Then in the docs PR, you opted to leave the current `contrib/gitlab.tpl` in place and the reason was just that it benefits users of older versions of GitLab.

My initial comment was about why I don't think _"all users"_ can just use GitLab's own template, regardless which GitLab version they are on. Even with GitLab offers free, out-of-box integration for everyone, as a user, I would love to see Trivy community to continue maintaining a template here, which enables various custom use cases (like @AljoschaP mentioned above), comparing to the opinionated GitLab first party Trivy integration that requires a docker daemon.

I think it is very related to the discussion above. 🙂

**Comment by julienvey** [comment]
Hi Guys,

Raising this closed issue, but I was thinking, any chance trivy could natively add a `gitlab` format that would use the template given above ? This way users could more easily integrate their trivy reports with Gitlab. Just thinking 😅

**Comment by knqyf263** [comment]
>I was thinking, any chance trivy could natively add a gitlab format that would use the template given above

I'm ok with that. We welcome contribution.
