### ISSUE TITLE
Unable to push Trivy security hub report to AWS security hub as its file size is greater than 240kb

### ISSUE THREAD

**Issue by saivenkateshedem** [aquasecurity/trivy#1732]
I have scanned my image with trivy and formatted to security hub report using [this](https://github.com/aquasecurity/trivy/blob/main/contrib/asff.tpl).However i got final report size as 275kb which aws security hub doesnt support.It should have file size less than 240kb. Is there any way we can reduce the size?

**Comment by DmitriyLewen** [comment]
Hello @saivenkateshedem 
Thanks for your interest in trivy.
You can use the `--severity` [flag](https://github.com/aquasecurity/trivy/blob/main/docs/getting-started/cli/image.md) and create 2 results with different severity, if that okay for you. 

Regards, Dmitriy

**Comment by saivenkateshedem** [comment]
Hello @DmitriyLewen 
Thanks for the solution.I have tried it but for one of the severity(LOW) while pushing it to security hub throwing below **error
An error occurred (InvalidInputException) when calling the BatchImportFindings operation: Invalid parameter 'Findings'. Size '109' is greater than maximum value: 100.**

AWS security hub allows only 100 requests per batch.Is it possible to even reduce the --severity LOW (Can we divide this)

**Comment by DmitriyLewen** [comment]
Hello @saivenkateshedem 
Thanks for your report.
Trivy is now unable to split the result file.
We will work to resolve your issue. 

Regards, Dmitriy

**Comment by LawrenceWarren** [comment]
Hi, is this being worked on? Trivy generating ASFF reports with >100 findings is a problem since SecurityHub only accepts reports with 100 or less findings.

Is there a way on Trivy's end, either with your ASFF template or some kind of confguration flag, that you can split a report into several reports with _N_ findings per report?

**Comment by DmitriyLewen** [comment]
Hello @LawrenceWarren 
Thank for your report!

We are working with this. 
When it will be ready, i will write to you!

Regards, Dmitriy

**Comment by StevenKitavi** [comment]
Hi, is this being worked on? Trivy generating ASFF reports with >100 findings is a problem since SecurityHub only accepts reports with 100 or less findings.

Is there a way on Trivy's end, either with your ASFF template or some kind of confguration flag, that you can split a report into several reports with N findings per report?

**Comment by StevenKitavi** [comment]
> Hello @LawrenceWarren Thank for your report!
> 
> We are working with this. When it will be ready, i will write to you!
> 
> Regards, Dmitriy

Hi Did you get a fix for this?

**Comment by DmitriyLewen** [comment]
Hello @StevenKitavi 
We refused this update and recommend just using `jq` to separate report - https://aquasecurity.github.io/trivy/v0.48/tutorials/integrations/aws-security-hub/#note

**Comment by StevenKitavi** [comment]
> Hello @StevenKitavi We refused this update and recommend just using `jq` to separate report - https://aquasecurity.github.io/trivy/v0.48/tutorials/integrations/aws-security-hub/#note

Hello @DmitriyLewen  thank you the first batch of 100 works how do i get the second?
I have a vulnerability count of 1300

**Comment by DmitriyLewen** [comment]
Just change range in array. e.g. for second -  `jq '.[100:200]' report.asff`
