### ISSUE TITLE
Adding a dedicated subcommand for SBOM generation

### ISSUE THREAD

**Issue by tamirkiviti13** [aquasecurity/trivy#1788]
I want to use trivy for SBOM generation, but the current command structure is inconvenient.

Currently the right way to use trivy for SBOM generation is:
- `trivy image --format cyclonedx my-image:tag` for docker containers.
- `trivy fs --format cyclonedx path/to/package` for language specifeic packages.

I would like to have a single dedicated subcommand for SBOM generation - `trivy sbom`, and trivy will figure out by itself which scan is needed (image or package).

The command should look like this:
`trivy sbom --format <SBOM_FORMAT> --output <OUTPUT_FILE_PATH> ARTIFACT_PATH` (--output is optional)

**Comment by knqyf263** [comment]
I don't think we need to move SBOM generation to `trivy sbom`. All other formats such as JSON can be specified as `--format` and SBOM is one of the report formats. It means `--format cyclonedx` can be specified as well as other formats so that the behavior can be consistent.

We can add `trivy sbom` in addition to the existing option.

**Comment by tamirkiviti13** [comment]
That's what I meant, the title and the description were not clear enough.
I edited the title to clearer.
