### ISSUE TITLE
CycloneDX VEX support

### ISSUE THREAD

**Issue by VinodAnandan** [aquasecurity/trivy#1836]
The known vulnerabilities inherited from the use of third-party and open-source software and the exploitability of the vulnerabilities can be communicated with CycloneDX.  This may help with this related issue - https://github.com/aquasecurity/trivy/issues/1831

CycloneDX VEX examples : https://github.com/CycloneDX/bom-examples/tree/master/VEX

Cc : @kaniini, @knqyf263, @masahiro331, @raesene, @stevespringett

**Comment by masahiro331** [comment]
We can't create vex, because our database doesn't have vulnerability analysis information.

In my opinion, CycloneDX vulnerability exploitability(VEX) has two factors.
https://cyclonedx.org/use-cases/#vulnerability-exploitability 

1. vulnerability assessment
  vulnerability assessment has CVE-id, CWEs, rating, and so on.
2. vulnerability exploitability 
  vulnerability exploitability has real effect justification, workaround, and so on. 

Trivy could be provided assessment, but exploitability can only be provided to the owner of each application.

**Comment by masahiro331** [comment]
Hi @VinodAnandan, @stevespringett, We are working on that now. 
https://github.com/aquasecurity/trivy/pull/1832

We can't create vex, because our database doesn't have vulnerability analysis information.

In my opinion, CycloneDX vulnerability exploitability(VEX) has two factors.
https://cyclonedx.org/use-cases/#vulnerability-exploitability 

1. vulnerability assessment
  vulnerability assessment has CVE-id, CWEs, rating, and so on.
2. vulnerability exploitability 
  vulnerability exploitability has real effect justification, workaround, and so on. 

Trivy could be provided assessment, but exploitability can only be provided to the owner of each application.

**Comment by itaysk** [comment]
@VinodAnandan could you please clarify what is the use case that you expect to be implement in Trivy?

**Comment by VinodAnandan** [comment]
@itaysk .The use cases I was looking for were:

- To improve the accuracy. If the exploitability data is available and can be provided in the output it will help with accuracy.
- For easier integration with other tools. It will be easier to integrate and communicate the BOM and vulnerability information with other tools.

**Comment by leahwsf** [comment]
Hey !
i need this feature for a project I’m working on and wanted to know if how it is going and maybe if you know when it will be done 
thanks by advance for the reponse :)
