### ISSUE TITLE
CVE-2020-36518 should be fixed in 2.13.2 in maven central but Trivy wants 2.14

### ISSUE THREAD

**Issue by neuwerld2** [aquasecurity/trivy#1872]
## Description
Today when building one of our applications we got a failure on the CVE-2020-36518. According to Trivy this should be fixed in version 2.14 of Jackson bind. 
According to https://github.com/FasterXML/jackson-databind 2.14 should be artifact version 2.13.2 in Maven central but when using 2.13.2 artifact as dependency in our application Trivy still say that this vulnerability exists.

## What did you expect to happen?
The check would complete without finding any vulnerabilities

## What happened instead?
Finds vulnerability that should be fixed but the version of Jackson bind is not 2.14 in Maven central but rather 2.13.2

**Comment by cwrau** [comment]
We seem to be getting the same error;

```
{
  "Results": [
    {
      "Target": "example.com/example (debian 11.2)",
      "Class": "os-pkgs",
      "Type": "debian"
    },
    {
      "Target": "Java",
      "Class": "lang-pkgs",
      "Type": "jar",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2020-36518",
          "PkgName": "com.fasterxml.jackson.core:jackson-databind",
          "PkgPath": "libs/jackson-databind-2.13.2.jar",
          "InstalledVersion": "2.13.2",
          "FixedVersion": "2.14",
          "Layer": {
            "DiffID": "sha256:REDACTED"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-36518",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Maven",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven"
          },
          "Title": "jackson-databind: denial of service via a large depth of nested objects",
          "Description": "jackson-databind before 2.13.0 allows a Java StackOverflow exception and denial of service via a large depth of nested objects.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-787"
          ],
          "CVSS": {
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-36518",
            "https://github.com/FasterXML/jackson-databind/commit/fcfc4998ec23f0b1f7f8a9521c2b317b6c25892b",
            "https://github.com/FasterXML/jackson-databind/issues/2816",
            "https://github.com/advisories/GHSA-57j2-w4cx-62h2",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-36518"
          ],
          "PublishedDate": "2022-03-11T07:15:00Z",
          "LastModifiedDate": "2022-03-18T19:52:00Z"
        }
      ]
    }
  ]
}
```

As you can see we're using jackson-databind 2.13.2, and this CVE is apparently fixed in 2.14, but 2.14 is not released yet 😅

We're running with `--ignore-unfixed`, fyi

**Comment by stickycode** [comment]
From https://nvd.nist.gov/vuln/detail/CVE-2020-36518

CVE-2020-36518 DetailCurrent Descriptionjackson-databind before 2.13.0 allows a Java StackOverflow exception and denial of service via a large depth of nested objects.

That is to say its fixed in any 2.13 version, this is super annoying and blocking lots of our builds. Simple fix?

**Comment by knqyf263** [comment]
@DmitriyLewen Can you take a look?

**Comment by stickycode** [comment]
Ive raised a pr in the GitHub advisory repo and on the vulnlist repo

**Comment by DmitriyLewen** [comment]
Hello @neuwerld2 , @cwrau, @stickycode 
Thanks for your report!

Trivy takes patched versions from [GitHub Advisory](https://github.com/advisories/GHSA-57j2-w4cx-62h2), where it is version 2.14.

Thanks @stickycode for your PR on GitHub!
@stickycode Your PR in `vuln-list` doesn't make sense, because [vuln-list-update](https://github.com/aquasecurity/vuln-list-update) automation updates vulnerabilities  in `vuln-list` and your changes will be removed after next update.

We must wait merge [PR151](https://github.com/github/advisory-database/pull/151).

Until that you can skip this vulnerabilities. [More information there](https://aquasecurity.github.io/trivy/v0.24.4/vulnerability/examples/filter/#by-vulnerability-ids)

Regards, Dmitriy

**Comment by DmitriyLewen** [comment]
Hi @neuwerld2 @cwrau 
PR151 merged.
Fixed version for [CVE-2020-36518](https://github.com/advisories/GHSA-57j2-w4cx-62h2) has been changed to 2.13.2.1.

Regards, Dmitriy

**Comment by neuwerld2** [comment]
Works like a charm. Thanks!
