### ISSUE TITLE
How to ignore specific files in a container? (to avoid false-positives)

### ISSUE THREAD

**Issue by chbiel** [aquasecurity/trivy#244]
We are scanning an image that contains https://github.com/golang/dep

Trivy reports issues for the file `go/src/github.com/golang/dep/website/yarn.lock`

As this folder contains the projects website code for https://golang.github.io/dep/ we are not interested in scanning that file and want to ignore it.

Ignoring the found CVE's is not a solution as it could be possible that other parts of the projects introduce that dependencies and we want to track them.

So can I ignore especially that file? Or is there a smarter way to achive this with trivy?
Thanks in advance

**Comment by christian-weiss** [comment]
As long as trivy do not support ignoring your package manager (yarn.lock) you could build to docker images:
a) a base image (without your yarn-app/yarn-package) - and scan it with trivy
b) an application image - no scan with trivy, but may want to skip building your app-image if you found a CRITICAL vulnerability in our base image...

Dockerfile with multi-stage is maybe of interested, too.

**Comment by chbiel** [comment]
thanks for your answer.

Maybe my question was a little bit misleading.
We don't want to disable "yarn" scanning at all. Especially for our own application that is important.

The issue here is, that trivy seem to scan all directories/files in the image and finds packages / yarn files that should not be scanned.
So the feature that we miss is something like a blacklisting of directories/files when scanning the image.

But as I understand your answer trivy currently does not have such feature, right?

**Comment by knqyf263** [comment]
@chbiel Thank you for reporting an issue! Trivy doesn't support the feature for now. But as you said, it seems useful. Let me consider how to achieve it. Or, iff you have any ideas, let me know.

**Comment by christian-weiss** [comment]
If you ignore a `.lock`-file then maybe other problems may creap in, you are not aware off, as a `.lock`-file can get changed (new dependencies, updated dependencies). If you are using a package manager / dependency manager, then you should get warned about problems and only ignore alerts which are proved by you to not be relevant (fine-graned ignore list).

If you want to maintain a serious level of trust between you as a docker image vendor and your community of docker image users. You should not utilize tools like vulnarabilitiy scanners to "fake" a trust level. You should also maintain a well defined ignore list (with reasons), no "bulk ignore". 

Instead of including source code of the go dependency manager in a docker image, you could install its binary or use a multi-stage Dockerfile to compile it from source in a previous step. 
You should feel responsible for all files (incl. source code, repo clones) that are included in your final docker image. So if you include the sources of go dependency manager, then you should feel responsible for its vulns. Bulk-ignoring is the worst decision in my opinion. A dirty hack would be to delete that `.lock`-file on build-time (via Dockerfile) before the docker image is scanned by trivy. 

A bulk-ignore and such a dirty-Dockerfile-hack is a K.O. for me if i select docker image vendors. My trust-level to you would drop to zero. JustMy2Ct.

@knqyf263 instead of "bulk-ignore" of some ".lock"-files, please focus more on ignoring a specific package (extend `.trivyignore` for that feature).

**Comment by chbiel** [comment]
@christian-weiss thanks for that detailed explaination! I will have a look if this is possible in our case.

But I still miss a more fine grained .trivyignore that maybe allows me to ignore a specific vuln in a specific file/dependency.

So my request was not the bulk ignore or something.
The core question here is: how do I exclude those finding, in that specific file/dependency.

Ignoring a whole file was one idea that is maybe achievable very easily but also introduce, as you explained correctly, some other potential problems like missing new finding.

so to sum up and include your feedback i would like to see a way to ignore CVE's through the trivyignore not only for the whole image but for parts of the image.

**Comment by heidemn** [comment]
1. Maybe it can be considered a bug of the `dep` package that it includes the `website` folder? (Because the average user of any package won't need its website assets.)
2. Similar to what was said before: If you're sure that you don't need the `website` folder, consider deleting it in your build process. Will also make your Docker image smaller.

**Comment by knqyf263** [comment]
@rahul2393 Could you implement `--skip-dirs` as a workaround? I think we need to extend this function so that a user can pass directories via the cli option.
https://github.com/aquasecurity/fanal/blob/master/walker/walk.go

**Comment by rahul2393** [comment]
@knqyf263  Ok will implement

**Comment by dgutson** [comment]
What's the ststus of this feature? Do you need help implementing it?
