### ISSUE TITLE
Need to scan image's misconfiguration information

### ISSUE THREAD

**Issue by yyy1000** [aquasecurity/trivy#2676]
Hi Team,

Recently, I want a security scanner to get the image's misconfiguration information, such as the Dockerfile which builds the image.

Now I try the command from the [documentation:](https://aquasecurity.github.io/trivy/v0.30.4/docs/misconfiguration/scanning/)

> trivy image --security-checks config IMAGE_NAME

, however, the result shows  "Detected config files: 0".

I can't get any misconfiguration information, is this because of my incorrect command? 
What kinds of misconfiguration can trivy detect from an image? I know it can detect some information from file system.

When I look through this project and try to run it by myself, I found it seems that trivy can get the Dockerfile builds the image, maybe we can get misconfiguration from that?

**Comment by Kilz78** [comment]
+1 
I really need it for my company (40k containers)

the goal of that is to implement some compliance check at image level :
- is the docker image run as root ?
- is the port 22 exposed ?
- is COPY command used instead of ADD

this is some basics check, but after we can enrich that : 
- Is the base image used for build this image match with those that we provide ?

piece of cake : we would like to implement those tests at harbor level, by this way, when a user try to push one image to the harbor repository, we have : 
- CVE scan + compliance checks of the dockerfile used to build this one.

**Comment by knqyf263** [comment]
Hopefully, we will include this feature in v0.37.0.
