### ISSUE TITLE
Integrate govulncheck to reduce false positives

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/trivy#2845]
Recently the go team announced govulncheck which can reduce the amount of false positives because it doesn't go purely off of libraries imported

https://go.dev/security/vuln/

> Integrations with [pkg.go.dev](https://pkg.go.dev/) and govulncheck to enable developers to find vulnerabilities in their projects. The [govulncheck command](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) analyzes your codebase and only surfaces vulnerabilities that actually affect you, based on which functions in your code are transitively calling vulnerable functions. Govulncheck provides a low-noise, reliable way to find known vulnerabilities in your projects.

currently trivy flags kube-bench as having [CVE-2020-8911](https://avd.aquasec.com/nvd/2020/cve-2020-8911/) when it doesn't actually use the S3 features of the `aws-sdk-go` library

https://github.com/aquasecurity/kube-bench/pull/1268

This can be helped by libraries being split into features like the new aws-sdk-go-v2 does but govulncheck also tackles this

**Comment by 06kellyjac** [comment]
govulncheck has now hit 1.0.0 and the API should be stable to integrate

https://go.dev/blog/govulncheck

**Comment by BronzeDeer** [comment]
When govulncheck was intially introduced I spent some time looking whether I could provide a PR for this, sadly the architecture of trivy seems to very strongly assume the "Every use of a dependency is  vulnerable" model (Which pre-govulncheck was very reasonable since most vuln databases only keep data at this granularity and code path analysis was hard to do automatically in many contexts). This architecture is great since it allows you to modularize the scanner into distinct parts, specifically :
1. parsing an artifact into a list of dependencies
1.  lookup of vulnerability state of each dependency/component. 

For govulncheck this model fails. since it needs to consider the artifact (atleast the binary) as a whole rather than sum of components, requiring a special case handling for go binaries that goes directly into govulncheck. It is doable but might require a deeper architecture discussion than just creating another language plugin etc.

**Comment by tamalsaha** [comment]
any updates on this? The false positives by the scanner is a real productivity killer.

**Comment by jmthomas** [comment]
I'm using [Redis alpine](https://github.com/docker-library/redis/blob/master/7.2/alpine/Dockerfile) which uses [gosu](https://github.com/tianon/gosu) which uses Go and they've even written up a [Security](https://github.com/tianon/gosu/blob/master/SECURITY.md) doc because they get so many false positives. Please add support for govulncheck!

**Comment by itaysk** [comment]
after discussing this further we decided to support this use case using VEX. govulncheck will be able to output VEX doc with the information necessary for Trivy to reduce the false positives https://github.com/golang/go/issues/62486. Trivy already supports consuming VEX. we might create a Trivy plugin to streamline this use case. Anyway, govulncheck will not be directly integrated into Trivy.

**Comment by elchenberg** [comment]
@itaysk Do you think that the Trivy Operator or the Harbor integration will be able to make use of what you outlined? :slightly_smiling_face:

**Comment by itaysk** [comment]
you would have to ask harbor about that. as for trivy (and operator), no, it will be be included

**Comment by AlexanderYastrebov** [comment]
> govulncheck will be able to output VEX doc with the information necessary for Trivy to reduce the false positives

govulncheck now supports `-format=openvex`, see https://github.com/golang/go/issues/62486

**Comment by silverwind** [comment]
Was this really fixed? Should it be re-opened?

Running `trivy fs --scanners vuln .` in a go project with `github.com/go-chi/chi/v5 v5.2.1` in `go.mod` and a app that does not use `middleware.RedirectSlashes` raises a false-positive for [this unreachable vulnerability](https://github.com/advisories/GHSA-vrw8-fxc6-2r93) which `govulncheck` apparently correctly identifies and suppresses. For me, this makes trivy unusable for go dependencies.

**Comment by jmthomas** [comment]
This should definitely be re-opened because without `govulncheck` Trivy will consistently report false positives.

**Comment by krzysztof-oneleet** [comment]
Can we look at reopening this as more and more false positives are becoming common?

**Comment by agwlnimish1985** [comment]
While the Vulnerability Exploitability eXchange (VEX) standard represents a standardized framework for decoupling security declarations from scanner engines, relying solely on VEX to solve the "noise" problem in containerized environments introduces severe operational bottlenecks. In the context of large-scale Kubernetes deployments and managed services, a central in-cluster scanner directly integrated with deep reachability analysis engines (like Go’s native govulncheck) delivers a far more resilient, verifiable, and secure outcome than a federated VEX publication model.

Market Landscape of Kubernetes and Managed Services has [82%](https://fosspost.org/kubernetes-adoption-rate-statistics/) of container users now run Kubernetes in production, [96%](https://www.cncf.io/blog/2025/01/30/digital-transformation-driven-by-community-kubernetes-as-example/) of enterprise organizations use Kubernetes in some form and [79%](https://fosspost.org/kubernetes-adoption-rate-statistics/) of organizations rely on managed Kubernetes services, shifting the burden of publishing VEX is not the right choice. 

[OpenSSF industry](https://openssf.org/blog/2026/01/08/signal-in-the-noise-an-industry-wide-perspective-on-the-state-of-vex/) notes that VEX adoption remains highly inconsistent and slow due to the sheer human effort required from under-resourced open-source maintainers.  Not to mention that A published VEX document is a static, point-in-time snapshot created during the build phase.

Instead of waiting for a fragmented ecosystem to publish VEX documents, integrating reachability analysis directly into a centralized cluster scanner (such as an admission controller or a Kubernetes Operator like the Trivy Operator) yields a superior security posture.

I would request the maintainers to reconsider the decision and provide a native support for govulncheck which provides the right result to all customer of Trivy with appropriate reachability analysis.

**Comment by destijl** [comment]
I'm the GKE security TL and have been involved in Kubernetes security since 2017. I see lots of container vuln scan reports from customers running various scanners on Kubernetes and GKE containers: the majority of K8s/GKE code is in golang. Consistently about 50% of those findings are false positives that could be eliminated by govulncheck.

I think the original conclusion here was too optimistic. If we play out all the things that need to happen:

- Users would know which programming languages are used in the containers they are scanning and know that golang needs special handling;
- They would know about govulncheck, and install it;
- They would understand what a vex statement is and how it should be used with Trivy; and
- They would run govulncheck and glue the vex output back into Trivy to eliminate half the findings.

That's not going to happen on any significant scale. Even if there's an optional plugin that does all that work, people won't know to turn it on. We have the technology to reliably eliminate massive amounts of false positives, but the scanner needs to do it by default, or customers will continue to waste time on false positives.

**Comment by 06kellyjac** [comment]
Generating your own vex document via govulncheck and then feeding that into your own CI if you've got a single go project is _relatively_ easy.

But if there's an image with 3+ go binaries you'd either have to generate or fetch vex documents for every single item.

---

DataDog have a "plugin" that can process the output of trivy to filter out false positives with govulncheck but it's limited to image scans and it's not easily usable with the action
https://github.com/DataDog/trivy-plugin-govulncheck

**Comment by agwlnimish1985** [comment]
This is not how customers are using Trivy. In nearly 100% of the cases, customers install trivy on a managed K8 cluster like GKE, AKS, EKS and perform a scan on the base vanilla cluster. 

It is at that time they witness a number of false positive in their report and the first yet rightful reaction is they freakout. I personally did a similar scan and passing the scan result from Trivy to govulncheck resulted in nearly 50% false positive. This can be easily avoidable with appropriate reachability integration such as govulncheck in the foundational scanner avoid stacked workflow for customer and save valuable time for all CSP's doing this on behalf of the customer.

**Comment by 06kellyjac** [comment]
I have literally no idea why you're arguing with me when my comment agrees with what you [originally said](https://github.com/aquasecurity/trivy/issues/2845#issuecomment-4961099816) and I'm the one who originally opened this feature request 4 years ago...

Also there's no "trivy customers", only trivy users or Aqua Enterprise customers.
