### ISSUE TITLE
Incorrect Nesting of asff.tpl

### ISSUE THREAD

**Issue by AndrewCharlesHay** [aquasecurity/trivy#2847]
The [CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/securityhub/batch-import-findings.html) needs a list of findings not an object with a list

**Comment by afdesk** [comment]
@AndrewCharlesHay thanks again for your interest in `Trivy`.

this issue about ASFF struct is well-known. I can see that you left  https://github.com/aquasecurity/trivy/issues/2023#issuecomment-1240959441 and also there is another issue #1898 about it.

An attribute `Findings` was added #1685 to fix #1684.
 
if i'm wrong, you can correct me. my opinion is next:

there are two ASFF struct: for the AWS CLI and for the AWS API. `Findings` need only for  the last one.
but the documentation about [ASFF syntax](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html) contains only one format with `Findings`.

Currently I don't know the best way to support two ASFF templates. If you know, please feel free to tell it. 

Using `jq` for mapping ASFF templates is a compromise.

as for me, there is more logic to use `jq` for covert into the CLI format, because a customer already uses CLI tool for uploading the report.

what do you think about it? thanks!

**Comment by AndrewCharlesHay** [comment]
That's a good point. We could make a separate file called something like `asff-cli.tpl` without the `Findings` wrapping

**Comment by afdesk** [comment]
> That's a good point. We could make a separate file called something like `asff-cli.tpl` without the `Findings` wrapping like #2854

I'm not sure that is a good way, because we need to support two `.tpl` files. ex., we have to add `secrets` to both of them

**Comment by knqyf263** [comment]
Using `jq` sounds a good compromise for now like @afdesk said.

**Comment by AndrewCharlesHay** [comment]
Ok I'll make a seperate PR for documentation on how to use jq
