### ISSUE TITLE
CSV report format

### ISSUE THREAD

**Issue by huornlmj** [aquasecurity/trivy#2945]
Please provide a CSV output type.

**Comment by huornlmj** [comment]
Ping

**Comment by itaysk** [comment]
I should be possible to create a CSV from existing output format, for example using a gotemplate or another tool.
For example, here's an example for creating a CSV that includes "AVDID" and "Severity" of misconfigurations: https://jqplay.org/s/hPFKiG2dbCr

**Comment by rmfranken** [comment]
Interesting that the table version contains less information than the JSON version. I like the table version much better, but it's hell to parse thanks to the fact that it's not csv. Is it really not a easy issue to output in csv natively instead of having to rely on another tool to do the conversion from JSON?

**Comment by itaysk** [comment]
everyone has different preferences when it comes to output formats. that's why we have decided to leave it to the community.
in addition, the raw json format is quite verbose and just dumping it to csv will create unusable table. also it is hierarchical by nature and does not translate easily into a flat table such as csv without some data mangling.
The native output of trivy is json and you should use it whenever possible, or convert to your preferred format.
