### ISSUE TITLE
Table output for version 0.32.0 isn't working

### ISSUE THREAD

**Issue by sjb94** [aquasecurity/trivy#3039]
## Description

when running the following command: 

trivy fs -s CRITICAL --ignore-unfixed . --output trivy.txt

the output is not in a table format, rather it has odd encodings for it. Even using the flag --format table does the same thing

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/17750671/196515793-642279cb-cb38-437d-a34c-c98f945c37f9.png">

## What did you expect to happen?
Usually the table output has a nice ascii table. This case it does not. Started seeing this issue with newer version. Tried version 0.32.1 as well

## Output of `trivy -v`:

![image](https://user-images.githubusercontent.com/17750671/196519140-13634e58-0752-41c7-a6a4-e9ac14e00d96.png)

**Comment by DmitriyLewen** [comment]
Hello @sjb94 
Thanks for your report!

Looks like you are running Trivy on Windows.
If true, Trivy does not currently work correctly on Windows.

Regards, Dmitriy

**Comment by DmitriyLewen** [comment]
@sjb94 
There is #2058 with information about adding support for Windows.
You can see progress there.
Also i added information about your problem.

**Comment by olljanat** [comment]
It looks to be that Trivy result is actually correct but because it is stored in UTF-8 format which old PowerShell or CMD cannot read. PowerShell 7 or Notepad++ does show correct output:
![image](https://user-images.githubusercontent.com/6213926/197156158-43f80317-6365-45fd-b2cd-55d1b9030480.png)

However most likely it still make sense to use ANSI encoding in Windows so those files are readable even with legacy tooling.

**Comment by sjb94** [comment]
Sorry for the late reply.
We figured out it was in fact an issue with our legacy Jenkins system. We
fixed it by telling Jenkins to read the console output as UTF8.

Thank you for help on this.

**Comment by DmitriyLewen** [comment]
Good!
I close this issue. If you still have a problem - feel free to reopen this issue.

Best Regards, Dmitriy
