### ISSUE TITLE
update compliance flag description

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3159]
update compliance flag description
it is require to fix compliance flag description :  
from : 
`comma-separated list of what compliance reports to generate (nsa)`

to:  
`compliance report to generate (nsa)`

**Comment by sourabhgupta385** [comment]
I get error like below with Trivy 0.34.0

`trivy --cache-dir /common-lab/trivy --debug k8s --skip-update --offline-scan --security-checks vuln --compliance nsa cluster --report summary

18:17:49  2022-11-10T12:47:49.382Z	FATAL	flag provided but not defined: -compliance`

**Comment by chen-keinan** [comment]
> I get error like below with Trivy 0.34.0
> 
> `trivy --cache-dir /common-lab/trivy --debug k8s --skip-update --offline-scan --security-checks vuln --compliance nsa cluster --report summary
> 
> 18:17:49 2022-11-10T12:47:49.382Z FATAL flag provided but not defined: -compliance`

the command you put look correct , also tested it exactly as you put it with `trivy v0.34.0` and I got results

could you please try the basic command format and let me know if it works for you:
```
trivy k8s cluster --compliance=nsa --report summary
```

**Comment by sourabhgupta385** [comment]
@chen-keinan 
> could you please try this basic command format and let me know if it works for you:
> 
> ```
> trivy k8s cluster --compliance=nsa --report summary
> ```

When I tried the command you provided, I got below error - 

> trivy --debug k8s cluster --compliance=nsa --report summary
DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
FATAL	All the results in the table format can mess up your terminal. Use "--report all" to tell Trivy to output it to your terminal anyway, or consider "--report summary" to show the summary output.

Then I ran like this - 

> 11:49:22  + trivy --debug k8s --timeout 30m0s --report summary cluster --compliance=nsa
11:49:22  2022-11-11T06:19:22.335Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
11:49:32  2022-11-11T06:19:32.411Z	DEBUG	cache dir:  /var/lib/jenkins/.cache/trivy
11:49:32  2022-11-11T06:19:32.411Z	DEBUG	There is no valid metadata file: unable to open a file: open /var/lib/jenkins/.cache/trivy/db/metadata.json: no such file or directory
11:49:32  2022-11-11T06:19:32.411Z	INFO	Need to update DB
11:49:32  2022-11-11T06:19:32.411Z	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
11:49:32  2022-11-11T06:19:32.411Z	INFO	Downloading DB...
11:49:32  2022-11-11T06:19:32.411Z	DEBUG	no metadata file
11:49:36  2022-11-11T06:19:36.220Z	DEBUG	Updating database metadata...
11:49:36  2022-11-11T06:19:36.220Z	DEBUG	DB Schema: 2, UpdatedAt: 2022-11-11 06:08:20.100096581 +0000 UTC, NextUpdate: 2022-11-11 12:08:20.100096281 +0000 UTC, DownloadedAt: 2022-11-11 06:19:36.220566757 +0000 UTC
12:05:00  
12:05:00  Summary Report for context-cywkmtemu2w
12:05:00  ┌─────────────────────┬──────────────────────────────────────────────────────────────┬─────────────────────────┬────────────────────┬───────────────────┐
12:05:00  │      Namespace      │                           Resource                           │     Vulnerabilities     │ Misconfigurations  │      Secrets      │
12:05:00  │                     │                                                              ├───┬─────┬─────┬────┬────┼───┬───┬───┬────┬───┼───┬───┬───┬───┬───┤
12:05:00  │                     │                                                              │ C │  H  │  M  │ L  │ U  │ C │ H │ M │ L  │ U │ C │ H │ M │ L │ U │
12:05:00  ├─────────────────────┼──────────────────────────────────────────────────────────────┼───┼─────┼─────┼────┼────┼───┼───┼───┼────┼───┼───┼───┼───┼───┼───┤
12:05:00  │ sonarqube           │ StatefulSet/sonarqube-sonarqube                              │   │     │     │    │    │   │ 1 │ 6 │ 26 │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ ConfigMap/kube-prometheus-stack-alertmanager-auth-proxy      │   │     │     │    │    │   │   │   │    │   │   │ 1 │   │   │   │
12:05:00  │ prometheus-operator │ StatefulSet/kube-prometheus-stack-grafana                    │   │     │     │    │    │   │   │ 8 │ 40 │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ StatefulSet/alertmanager-kube-prometheus-stack-alertmanager  │   │     │     │    │    │   │   │ 3 │ 19 │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ Deployment/kube-prometheus-stack-operator                    │   │     │     │    │    │   │   │   │ 9  │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ DaemonSet/kube-prometheus-stack-prometheus-node-exporter     │   │     │     │    │    │   │ 3 │ 2 │ 10 │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ StatefulSet/prometheus-kube-prometheus-stack-prometheus      │   │     │     │    │    │   │   │ 4 │ 23 │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ Deployment/kube-prometheus-stack-prometheus-adapter          │   │     │     │    │    │   │   │   │ 7  │   │   │   │   │   │   │
12:05:00  │ prometheus-operator │ ConfigMap/kube-prometheus-stack-prometheus-auth-proxy        │   │     │     │    │    │   │   │   │    │   │   │ 1 │   │   │   │
12:05:00  │ prometheus-operator │ ConfigMap/kube-prometheus-stack-grafana-auth-proxy           │   │     │     │    │    │   │   │   │    │   │   │ 1 │   │   │   │
12:05:00  │ prometheus-operator │ Deployment/kube-prometheus-stack-kube-state-metrics          │   │     │     │    │    │   │   │ 2 │ 10 │   │   │   │   │   │   │
12:05:00  │ kube-system         │ Deployment/tiller-deploy                                     │ 3 │ 22  │ 138 │ 3  │    │ 1 │   │ 2 │ 9  │   │   │   │   │   │   │
12:05:00  │ kube-system         │ Deployment/kubernetes-dashboard                              │ 3 │ 22  │ 117 │ 2  │    │   │ 1 │ 2 │ 10 │   │   │   │   │   │   │

It did give cluster level report but this is not compliance nsa report that I expected. I am expecting report to be the one that's present at https://aquasecurity.github.io/trivy/v0.34/docs/kubernetes/cli/compliance/ as screenshot.

**Comment by chen-keinan** [comment]
true this is not compliance report , but I'm unable to reproduce the problem, can you share info on your env. ?  is it air-gapped ?
I'll be happy to jump on a call next week (to look for root cause) if you want

**Comment by sourabhgupta385** [comment]
@chen-keinan It's not really air-gapped env but we will be having it in future. Currently we download the DB at one location and then use it in commands using cache-dir. But for testing purpose I am not doing it that way as well. 

I'm using Oracle Linux and Trivy version is 0.34.0 . 

I installed Trivy in my Jenkins slave like this
`rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.rpm`

I can't share much details as well over the call because of organization policies. I hope you understand. Let me know if I should try an older version or something else?

Thanks

**Comment by chen-keinan** [comment]
@sourabhgupta385 I'm looking to do the basic test , do you have access to k8s cluster from your desktop (via kubectl) if so could you try install `trivy` on your desktop and run this :
`trivy k8s cluster --compliance=nsa --report summary`

**Comment by sourabhgupta385** [comment]
@chen-keinan I installed Trivy on the bastion and did the test as 

> trivy --debug k8s cluster --timeout 30m0s --compliance=nsa --report summary
2022-11-11T11:54:00.379Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-11-11T11:54:06.368Z	DEBUG	cache dir:  /root/.cache/trivy
2022-11-11T11:54:06.368Z	DEBUG	DB update was skipped because the local DB is the latest
2022-11-11T11:54:06.368Z	DEBUG	DB Schema: 2, UpdatedAt: 2022-11-11 06:08:20.100096581 +0000 UTC, NextUpdate: 2022-11-11 12:08:20.100096281 +0000 UTC, DownloadedAt: 2022-11-11 11:36:00.89425828 +0000 UTC
157 / 994 [---------------------------->______________________________________________________________________________________________________________________________________________________] 15.79% 0 p/s
157 / 994 [---------------------------->______________________________________________________________________________________________________________________________________________________] 15.79% 0 p/s
157 / 994 [---------------------------->______________________________________________________________________________________________________________________________________________________] 15.79% 0 p/s
994 / 994 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s

Summary Report for compliance: nsa
┌──────┬──────────┬──────────────────────────────────────────────────────────┬────────────┐
│  ID  │ Severity │                       Control Name                       │ Compliance │
├──────┼──────────┼──────────────────────────────────────────────────────────┼────────────┤
│ 1.0  │ MEDIUM   │                   Non-root containers                    │   94.07%   │
│ 1.1  │ LOW      │             Immutable container file systems             │   79.59%   │
│ 1.2  │ HIGH     │             Preventing privileged containers             │   99.43%   │
│ 1.3  │ HIGH     │           Share containers process namespaces            │  100.00%   │
│ 1.4  │ HIGH     │              Share host process namespaces               │   99.19%   │
│ 1.5  │ HIGH     │                   Use the host network                   │   99.77%   │
│ 1.6  │ LOW      │  Run with root privileges or with root group membership  │   0.00%    │
│ 1.7  │ MEDIUM   │         Restricts escalation to root privileges          │   79.07%   │
│ 1.8  │ MEDIUM   │        Sets the SELinux context of the container         │  100.00%   │
│ 1.9  │ MEDIUM   │ Restrict a container's access to resources with AppArmor │   77.83%   │
│ 1.10 │ LOW      │   Sets the seccomp profile used to sandbox containers.   │   77.83%   │
│ 1.11 │ MEDIUM   │          Protecting Pod service account tokens           │  100.00%   │
│ 1.12 │ MEDIUM   │    Namespace kube-system should not be used by users     │   97.93%   │
│ 2.0  │ MEDIUM   │           Pod and/or namespace Selectors usage           │  100.00%   │
│ 3.0  │ CRITICAL │      Use CNI plugin that supports NetworkPolicy API      │   0.00%    │
│ 4.0  │ MEDIUM   │      Use ResourceQuota policies to limit resources       │   0.00%    │
│ 4.1  │ MEDIUM   │        Use LimitRange policies to limit resources        │   0.00%    │
│ 5.0  │ CRITICAL │            Control plan disable insecure port            │   0.00%    │
│ 5.1  │ CRITICAL │                Encrypt etcd communication                │  100.00%   │
│ 6.0  │ CRITICAL │            Ensure kube config file permission            │   0.00%    │
│ 6.1  │ CRITICAL │       Check that encryption resource has been set        │  100.00%   │
│ 6.2  │ CRITICAL │                Check encryption provider                 │  100.00%   │
│ 7.0  │ CRITICAL │            Make sure anonymous-auth is unset             │  100.00%   │
│ 7.1  │ CRITICAL │            Make sure -authorization-mode=RBAC            │  100.00%   │
│ 8.0  │ HIGH     │                Audit policy is configure                 │   0.00%    │
│ 8.1  │ MEDIUM   │               Audit log path is configure                │  100.00%   │
│ 8.2  │ MEDIUM   │                     Audit log aging                      │  100.00%   │
└──────┴──────────┴──────────────────────────────────────────────────────────┴────────────┘

It worked from there. I expect it to work from Jenkins pipelines as well. As I am thinking to have some automation engineered from there. Like periodic scan and alert trigger.

**Comment by chen-keinan** [comment]
@sourabhgupta385 , great. thanks for checking just wanted to make sure basic is working.
if you are using it via jenkins maybe you can using the `--format json` flag rather then table
