### ISSUE TITLE
Add support for Wolfi OS

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy#3205]
Wolfi is based on Alpine, but they have their own advisories

https://www.chainguard.dev/unchained/introducing-wolfi-the-first-linux-un-distro

**Comment by luhring** [comment]
Hi @afdesk! 👋  Thanks for opening this issue. I just noticed it today, along with the draft PRs you've opened!

Funny timing, I think we started looking at adding Wolfi support to Trivy around the same exact time! 😄 

I'm on the Wolfi team, but this is my first contribution to Trivy. If you have the time, I'd love to know what you think of the code I've submitted, and to learn if there's an opportunity to improve what I have.

**Comment by bureado** [comment]
See #2933, maybe this will help with that.

**Comment by afdesk** [comment]
> Hi @afdesk! wave Thanks for opening this issue. I just noticed it today, along with the draft PRs you've opened!
> 
> Funny timing, I think we started looking at adding Wolfi support to Trivy around the same exact time! smile
> 
> I'm on the Wolfi team, but this is my first contribution to Trivy. If you have the time, I'd love to know what you think of the code I've submitted, and to learn if there's an opportunity to improve what I have.

Hi @luhring ! It's really funny story )

You did a great job, you have tests and updated the docs. cool!
thanks for your time and efforts!

I looked a little at your PRs, and it seems the updates repeats a logic for alpine packages.
Are there any reasons for it? 

I'd prefer to use the current alpine code. 

also can we merge our branches?

what do you think about it?

**Comment by luhring** [comment]
Thanks! Great point on looking for streamlining opportunities with Alpine.

I'm wondering if I can even delete what I added at `pkg/fanal/analyzer/os/wolfi/...`, relying instead on `pkg/fanal/analyzer/os/release/release.go` to detect the Wolfi OS. What do you think?

>also can we merge our branches?

I'm up for it! Does it make sense to start with my branch, since there's an end-to-end working solution here, and improve the code from there?

One last thought — there might be some sense in keeping Alpine and Wolfi logic separate in **_certain places_** to avoid complexity. While the two distros share some common traits today, these are two separate and independent projects from one another. There's not an upstream/downstream relationship or anything like that. Wolfi is already different in some respects today (as noted [here](https://github.com/aquasecurity/vuln-list-update/pull/183#issue-1460544583)), and is likely to continue to diverge over time.

Thanks for your time!

**Comment by afdesk** [comment]
@luhring  I agree that it makes sense to start with your branch. 
I'll try to move my change into your PRs soon (1-2 days).

Told me please, as a member of the Wolfi team, are there any plans to change of Wolfi security advisories format? I mean now you use Alpine's struct, but maybe you want to change it )

also do i understand correctly that we can't apply any Alpine's advisories to Wolfi distro? just to confirm it )

**Comment by luhring** [comment]
> I agree that it makes sense to start with your branch.
> I'll try to move my change into your PRs soon (1-2 days).

Sounds great! Thanks!

> are there any plans to change of Wolfi security advisories format? I mean now you use Alpine's struct, but maybe you want to change it )

Good question — it's something we've been talking about recently. Generally, we'd try to keep any changes backward compatible, but we have recently discussed a few enhancements to the data structure.

> also do i understand correctly that we can't apply any Alpine's advisories to Wolfi distro? just to confirm it )

That's correct — Alpine data **should not** be used with Wolfi images, and vice versa. Wolfi patches, builds, and distributes its software completely separately from Alpine, so security data from one distro is not applicable to another distro.

**Comment by kaniini** [comment]
@knqyf263 can you look at this?

**Comment by knqyf263** [comment]
I'm on sick leave now. I'll take a look after I get better.

**Comment by afdesk** [comment]
@luhring sorry for waiting. there is an urgent task. i'll do it soon
