### ISSUE TITLE
This version does not have 2.7.1 version, and the highest version is 0.40.1. Is this vulnerability a false positive?

### ISSUE THREAD

**Issue by fengshunli** [aquasecurity/trivy#3409]
## What did you expect to happen?

![image](https://user-images.githubusercontent.com/18587688/211581041-10faf39f-fcb0-405f-9aed-f60bdcf683f5.png)

## Output of run with `-debug`:

```
(paste your output here)
```

## Output of `trivy -v`:

```
(paste your output here)
```

**Comment by DmitriyLewen** [comment]
Hello @fengshunli 
Thanks for your report!

`https://github.com/prometheus/prometheus` has problem with Go dependency versioning.

I am closing this issue, because it duplicate of https://github.com/aquasecurity/trivy/issues/2992. 
You can find more information about this problem in this issue.

Regards, Dmitiry
