### ISSUE TITLE
Include DevDependencies scans for npm packages

### ISSUE THREAD

**Issue by NicolasOmar** [aquasecurity/trivy#3742]
Hello team. I hope this message/issue finds you well.
Yesterday I [created a discussion](https://github.com/aquasecurity/trivy/discussions/3714) explaining my situation where I have a repository that uses [npm and only devDependencies](https://github.com/NicolasOmar/reactive-bulma/blob/main/package.json).
The situation related to the repo's package-lock.json is that I wanted to integrate [Trivy's Github Action](https://github.com/aquasecurity/trivy-action) to find new vulnerabilities, and given the fact it does not look at [development-level dependencies](https://aquasecurity.github.io/trivy/v0.37/docs/vulnerability/detection/language/).

My question. Is there a chance to include them as scannable in a future version?

Thank you for your time.

**Comment by knqyf263** [comment]
We don't have a plan to support it, but we welcome contributions.

**Comment by reneoelke** [comment]
I have the same problem. OSV, Grype and `npm audit` are finding critical vulnerabilities in devDependencies which were not found with Trivy. This is a big problem because we have to prevent supply chain attacks in our pipelines before installing any of the dependencies (i.e. for unit testing etc.). All dependencies will be installed with `--ignore-scripts`. But when running tests, insecure packages could still cause significant damage to the pipeline.

The other reason for including devDependency scanning as default would be that Trivy finds all vulnerabilities when scanning via SBOM file (i.e. created before with `syft packages . --output cyclonedx-json | trivy sbom -`.

**Comment by NicolasOmar** [comment]
Thank you for your work team, I appreciate such an effort.

**Comment by knqyf263** [comment]
Luckily, we managed to include it in v0.43.0. Yarn and pnpm support will be coming soon.
