### ISSUE TITLE
download trivy DB from private repo

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3891]
## Description
it is require to add support for downloading trivy DB from private repo.

**Comment by EnginKosure-ASML** [comment]
I have a similar problem that I would like to mention here:
I have pulled the trivy-db image using oras and pushed it to the private google artifact registry.
When  scan-vulnerabilityreport pods are being created, the initcontainers are stuck at the database download stage. 

The error log is something like that:
trivy --cache-dir /tmp/trivy/.cache image --download-db-only --db-repository private.google.artifact.reg/trivy-db -d
2023-03-23T13:13:51.935+0100    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-23T13:13:51.939+0100    DEBUG   cache dir:  /tmp/trivy/.cache
2023-03-23T13:13:51.939+0100    DEBUG   There is no valid metadata file: unable to open a file: open /tmp/trivy/.cache/db/metadata.json: no such file or directory
2023-03-23T13:13:51.939+0100    INFO    Need to update DB
2023-03-23T13:13:51.939+0100    INFO    DB Repository: private.google.artifact.reg/trivy-db
2023-03-23T13:13:51.939+0100    INFO    Downloading DB...
2023-03-23T13:13:51.939+0100    DEBUG   no metadata file
2023-03-23T13:13:53.182+0100    FATAL   init error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:419
  - DB error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.NewRunner
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:130
  - failed to download vulnerability DB:
    github.com/aquasecurity/trivy/pkg/commands/operation.DownloadDB
        /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:117
  - OCI artifact error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).Download
        /home/runner/work/trivy/trivy/pkg/db/db.go:155
  - OCI artifact error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).initOCIArtifact
        /home/runner/work/trivy/trivy/pkg/db/db.go:205
  - unacceptable media type: application/vnd.oci.image.layer.v1.tar+gzip:
    github.com/aquasecurity/trivy/pkg/oci.NewArtifact
        /home/runner/work/trivy/trivy/pkg/oci/artifact.go:102
        
        My question is what is the correct media type for the image?

If I upload the image by building myself using your github repo, then the error is annotation error: org.opencontainers.image.title is missing. 

So both recommended ways of uploading the trivy-db to a private repo are failing in my case. Could you please add some clarification to the docs?
        Thank you.

**Comment by knqyf263** [comment]
`docker login` should work. `TRIVY_PASSWORD` may not work.

**Comment by EnginKosure-ASML** [comment]
> `docker login` should work. `TRIVY_PASSWORD` may not work.

Thank you for the answer. But docker pull doesn't work for the trivy-db image. Fails with the code: unsupported media type application/vnd.aquasec.trivy.config.v1+json. 

Trivy password is not the case, the failure happens inside the container. Is there a configuration parameter to pass to the operator in valus.yaml file?
When I execute the command (the init container tries to execute, ```trivy --cache-dir /tmp/trivy/.cache image --download-db-only --db-repository private.repo.path/trivy-db ```) both within the container (```kubectl exec -it -n trivy-system scan-vulnerabilityreport-b5f875f4f-pksnf -c  95eba412-19ef-4228-b07e-a3d363bde194 -- sh
```) or local terminal, I got the above error.

**Comment by EnginKosure-ASML** [comment]
> > Thank you for the answer.
But docker pull doesn't work for the trivy-db image. Fails with the code: unsupported media type application/vnd.aquasec.trivy.config.v1+json.
> 
> No, I mean `docker login` configures the credential. Trivy will read it.

Thank you for the answer  @knqyf263 . 

Unfortunately, the scan-vulnerabilityreport-xxxxxxx  pods that is being created by trivy-operator does not have docker util. 

We don’t want to whitelist any public repository (ghcr.io and pkg-containers.githubusercontent.com in this case).

We want to download trivy-db from our private google artifact registry.
As far as I understand, you don’t have support for that.

When I check the error log:
```
"stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob
/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:254
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1
/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:79
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/reconcile/reconcile.go:102
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
[/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122)
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
[/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
[/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235)"}
```

I assume the problem is happening https://github.com/aquasecurity/trivy/blob/main/pkg/oci/artifact.go#L59-L68
More precisely the DefaultKeyChain I think: https://github.com/google/go-containerregistry/blob/main/pkg/authn/README.md#tldr-for-consumers-of-this-package
It will try to look for credentials underneath ~/.docker/config.json
But we don’t have it in the pods that is being created by trivy-operator.(scan-vulnerabilityreport-xxxxxxx pods)

To summarize; 
Scanning images from private registry with credentials works (with service account/workload idedntity in my case). But this service account isn’t being used to download the trivy-db, if the trivy-db is in the same private registry like the images. To download the trivy-db from a private registry the credentials have to be set in ~/.docker/.config.json. But there is no configurable key in the helmrelease values.yaml file (https://github.dev/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml)

It would be great to have environment variables or any sort of configurable value field for downloading the trivy-db from a private registry.

But meanwhile, could you please provide some guidance about the best approach for a temporary solution? 
For example as far as I see, we only have access to the tmp folder in the scan-vulnerabilityreport-init containers. To be able to create the root/.docker/.config.json, what would be your suggestion? Running as root would need extra policy adjustments in my setup, so I don’t want to try that, since the chance is high that it won’t solve the problem. Or is there an easier/better/safer approach?
Would using built-in trivy server in cluster help?
Thank you in advance for your answer.
