### ISSUE TITLE
remove unused volume and volume mounts from node-collector

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy#3926]
it is required to remove unused volume and volume mounts from node-collector job

**Comment by EnginKosure-ASML** [comment]
Hi @chen-keinan,

I would like to mention a node-collector volume path-related issue here.

We use GKE and the path to /opt/cni/bin/ can't be created by the trivy-operator triggered jobs. Because GKE changes opt-cni-bin path by default to home/kubernetes/cni. So the folder can't be found, and the creation of the sub-folder fails.

Would it be possible to make that part configurable via helm release values.yaml file? 

I see that you added recently the "node-collector pod volumeMounts definitions" to values.yaml file, but I have tested it by overwriting the path with the one that GKE expects, still the node collector pods fail to be created. Could you please check that on your side? I am ready to make the testing on GKE and provide the results if needed.

Thank you in advance
