### ISSUE TITLE
Support BusyBox base image

### ISSUE THREAD

**Issue by nicksc423** [aquasecurity/trivy#397]
Currently when scanning BusyBox images Trivy throws a FATAL error:
`FATAL	error in image scan: failed to scan the image: failed to analyze OS: Unknown OS`

It'd be nice to add support for BusyBox

**Comment by mattlorimor** [comment]
Since BusyBox doesn't have any way to install system packages, the most I would expect Trivy to do at this point would be to pull the BusyBox version using something like this;

```
/ # busybox | head -1
BusyBox v1.31.1 (2020-04-14 01:09:51 UTC) multi-call binary.
```

Then compare the version against known CVEs for that BusyBox version. I am not quite sure where the vuln feed would come from, though. There have certainly been [CVEs for BusyBox in the past](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe%3A%2Fa%3Abusybox%3Abusybox%3A1.10.0).

As for scanning for application dependencies, I would expect that Trivy could continue on as normal on BusyBox simply looking for the application dependency manifests (e.g., `.lock` files) it already looks for.

**Comment by mattlorimor** [comment]
The NVD database should technically have this data to compare against in the CPE fields, but I'm not sure what capability the current Trivy code has to compare against that in this way.

https://github.com/aquasecurity/vuln-list/blob/9fe1471a12139e35fb0b63cfe7cd5a82873f0db3/nvd/2019/CVE-2019-5747.json#L8

**Comment by simar7** [comment]
Thanks for digging into this @mattlorimor, we're currently investigating this as well. Your feedback is helpful!

**Comment by knqyf263** [comment]
Now, Trivy can handle a busybox image gracefully, but it doesn't mean Trivy can detect vulnerabilities of busybox itself. Someone who needs it can watch this issue.
https://github.com/aquasecurity/trivy/issues/481
