### ISSUE TITLE
Scan kubernetes pods?

### ISSUE THREAD

**Issue by san3jaya** [aquasecurity/trivy#420]
Is there a way to scan kubernetes pods with this? If can what is the way?
like : trivy [POD_NAME]

**Comment by knqyf263** [comment]
Actually, we're working on it, but the tool is still a private repository. Trivy itself doesn't support it. Please wait a while. CC. @danielpacak

**Comment by itaysk** [comment]
@wipflash will a kubectl plugin solve your need? https://github.com/itaysk/kubectl-trivy

```
kubectl trivy pod mypod
kubectl trivy deployment mydeployment
```

**Comment by san3jaya** [comment]
@itaysk This one working as expected.

**Comment by DrissiReda** [comment]
@itaysk is it possible to do this from the inside of the kubernetes cluster inside a pod? I want to have a cronjob that scans all pods in a select namespace, since I won't know where this pod will be scheduled I don't know if images will be there, I also use containerd, can I just have a pod with trivy image and bind the hostPath where we have all the pods? Also if you know which path is that, could you tell me ? 
Thanks in advance

**Comment by knqyf263** [comment]
As we discussed [here](https://github.com/aquasecurity/trivy/issues/848), you can use [Starboard](https://github.com/aquasecurity/starboard).
