### ISSUE TITLE
Non-commercial vs commercial usage: which data sources?

### ISSUE THREAD

**Issue by itamarst** [aquasecurity/trivy#491]
The README says some of the data sources are only licensed for non-commercial usage. It's difficult for me as a potential user to tell whether I can or cannot use trivy in a particular scenario.

It would be useful to have:

1. A flag that disables sources that are non-commercial-use-only.
2. Documentation of which sources are non-commercial-use-only, and the impact of the flag if it's implemented.

Thank you!

**Comment by kgeorgiou** [comment]
👋 Just a fan of Trivy here. That's a great point! 

These are the data source licenses I managed to collect so far:

**Language Specific Data Sources** (https://github.com/aquasecurity/trivy#data-sources):

- ✅ [GitHub Advisories](https://github.com/advisories) - [Creative Commons Attribution 4.0 license](https://docs.github.com/en/github/site-policy/github-additional-product-terms#12-advisory-database)
- ✅ [PHP Security Advisories Database](https://github.com/FriendsOfPHP/security-advisories) - [The Unlicense](https://github.com/FriendsOfPHP/security-advisories/blob/master/LICENSE)
- ❌ [Safety DB](https://github.com/pyupio/safety-db) - [Creative Commons Attribution-NonCommercial 4.0 International](https://github.com/pyupio/safety-db/blob/master/LICENSE.txt)
- ✅  [Ruby Advisory Database](https://github.com/rubysec/ruby-advisory-db) - [No License](https://github.com/rubysec/ruby-advisory-db/blob/master/LICENSE.txt) [**\***](https://github.com/rubysec/ruby-advisory-db/pull/449)
- ✅ [Node Ecosystem Security Working Group](https://github.com/nodejs/security-wg) - [MIT License](https://github.com/nodejs/security-wg/blob/master/LICENSE.md)
- ✅ [RustSec Advisory Database](https://github.com/RustSec/advisory-db) - [CC0 1.0 Universal Public Domain Dedication](https://github.com/RustSec/advisory-db/blob/master/LICENSE.txt)


**OS Data Sources** (https://github.com/aquasecurity/vuln-list):
- ❓ [Alpine Linux Bug Tracker](https://bugs.alpinelinux.org/projects/alpine/issues)
- ❓ [Amazon Linux Security Center](https://alas.aws.amazon.com/)
- ❓ [Amazon Linux Security Center 2](https://alas.aws.amazon.com/alas2.html)
- ❓ [Debian Security Bug Tracker](https://security-tracker.debian.org/tracker/)
- ❓ [National Vulnerability Database](https://nvd.nist.gov/)
- ❓ [Debian GNU/Linux OVAL](https://www.debian.org/security/oval/)
- ✅ [Security Data](https://www.redhat.com/security/data/metrics/) - [Creative Commons Attribution 4.0 license](https://www.redhat.com/security/data/metrics/)
- ❓ [Ubuntu CVE Tracker](https://people.canonical.com/~ubuntu-security/cve/)
- ❓ [OpenSUSE/SLES SUSE Security CVRF](http://ftp.suse.com/pub/projects/security/cvrf/)
- ❓ [Photon Security Advisory](https://vmware.bintray.com/photon_cve_metadata/)

Now regarding a flag for using only commercial friendly data sources, I think the change has to first happen at [trivy-db](https://github.com/aquasecurity/trivy-db) since that's where the [database file](https://github.com/aquasecurity/trivy-db/releases) Trivy fetches is [compiled](https://github.com/aquasecurity/trivy-db/blob/master/Makefile#L66-L73) every 12 hours.

**Comment by P1ng-W1n** [comment]
It would be definitely useful to have this option, especially as there are additional data sources used by Trivy (for example the Github Advisory Database used by pkg/vulnsrc/ghsa/ghsa.go (referenced by pkg/vulnsrc/vulnsrc.go)). 
Those are seem to licensed under the Creative Commons Attribution 4.0 license (https://docs.github.com/en/github/site-policy/github-additional-product-terms#12-advisory-database) but this doesn't mean that an other data source wouldn't be added to the repo later on (with a license that's not for commercial use)

**Comment by knqyf263** [comment]
It makes sense. In fact, we're now considering the option. As for ruby-advisory-db, it includes some data from OSVDB which doesn't allow commercial usage. Now, we're trying to remove those data to make it a commercial friendly data source.
https://github.com/rubysec/ruby-advisory-db/pull/456

After this PR gets merged, we can add the option.

**Comment by dberecz** [comment]
I'd like to ask if there is any update on this topic? I cannot find such flag in the documentation, neither an official list of the sources that can be used in commercial/non-commercial scenarios. If neither are available, what would be the best way to contribute?

**Comment by timmeinerzhagen** [comment]
Seems like SafetyDB is getting dropped from trivy.

* trivy-db already dropped SafetyDB aquasecurity/trivy-db#173
* trivy has the PR for it aquasecurity/trivy#1580

**Comment by knqyf263** [comment]
Yes, we finally dropped Python Safety DB from Trivy DB👍  [Trivy DB v2](https://github.com/aquasecurity/trivy-db/pkgs/container/trivy-db/13076594?tag=2) is available for commercial use.
https://github.com/aquasecurity/trivy-db/issues/173

The next version v0.23.0 of Trivy CLI will start using Trivy DB v2. Note that the current latest version v0.22.0 still refers to [Trivy DB v1](https://github.com/aquasecurity/trivy-db/releases).
