### ISSUE TITLE
Trivy version 0.44 panics with assignment to entry in nil map for npm repository

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy#4923]
### Discussed in https://github.com/aquasecurity/trivy/discussions/4907

Trivy returns error, if `package-lock.json` file doesn't contains root `Dependencies` field(packages[""].Dependencies) , but does have links.

**Comment by woodsjd-cr** [comment]
Hi, I still have this exact issue. However, hen I manually add to the package-lock.json the following - > field(packages[""].dependencies={}, 
I am able to run 'trivy fs <path to project>' without errors and receive the report correctly.
This of course isnt great because we shouldnt manually update the package-lock.json but also because on 'npm install' the change will be undone

**Comment by DmitriyLewen** [comment]
Hello @woodsjd-cr 
Thanks for your information!

We know about this problem and [fixed](https://github.com/aquasecurity/trivy/pull/4936) it.
[v0.44.1](https://github.com/aquasecurity/trivy/milestone/24) will include this fix.
But your solution will be useful until next release.
Thanks!

**Comment by knqyf263** [comment]
v0.44.1 was out.

**Comment by woodsjd-cr** [comment]
Boom! great job, thank you!
