### ISSUE TITLE
Trivy Scan: FATAL error seen while running the trivy scan

### ISSUE THREAD

**Issue by ramsanka** [aquasecurity/trivy#5463]
Observing the following error -: 

[31mFATAL[0m	report error: unable to write results: failed to write results: failed to write with template: template: output template:88:60: executing "output template" at <.Type>: wrong type for value; expected string; got types.TargetType

**Comment by jaapspiering** [comment]
I ran into the same exception message. Turned out the HTML template I was specifying was not the same as the one for my current Trivy version. There is a recent change that I didn't have, causing this exception:

https://github.com/aquasecurity/trivy/commit/44656f285323491a72a37e6a90a203059d891253#diff-2cd0cbc37b819eeeae50cba02ee81b39e4e31ab9b3ea664811f9919d84c0d2eb
