### ISSUE TITLE
Gradle dependency tree support

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#5947]
## Description

Description
License is not yet supported for `gradle.lockfile`.
https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/java/

![image](https://github.com/aquasecurity/trivy/assets/2253692/d46b8354-7ef5-4dde-a5d7-8685821f1dfc)

We probably need to parse `build.gradle` and `pom.xml` in cache dirs.

**Comment by ChristianCiach** [comment]
> We probably need to parse `build.gradle` and `pom.xml` in cache dirs.

You probably mean the correct thing, but just to be sure: There are no `pom.xml` and `build.gradle` for cached dependencies. You *probably* mean `*.pom` and `*.module` files. 

Scanning the `.pom` files seems like a great idea. But you probably don't seed to scan the `.module` files, because I've never seen a Gradle module-metadata file that contains licenses. In fact, according to the specification, I believe that these files *cannot* contain license information: https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/src/docs/design/gradle-module-metadata-latest-specification.md
