### ISSUE TITLE
feat(ruby): support gemspec

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#700]
Currently, Trivy traverses all paths and looks for all Gemfile.lock in a container image. However, the image sometimes has only Gemfile.lock and doesn't install gems listed in the Gemfile.lock. I think a gem should have *.gemspec file if it is installed. e.g. `rake.gemspec` has the information about `rake`.

To avoid false positives from Gemfile.lock, we are probably able to take advantage of `*.gemspec` file.

How it works:

1. Look for all *.gemspec files
1. Parse those files
1. Extract a gem name and version
1. Use them for vulnerability detection

How to implement it:
1. Add a new parser [here](https://github.com/aquasecurity/go-dep-parser/tree/master/pkg) like `pkg/gem/parse.go`
1. Add a new analyzer [here](https://github.com/aquasecurity/fanal/tree/master/analyzer/library) like `analyzer/library/gem/gem.go`
1. Add a new detector [here](https://github.com/aquasecurity/trivy/tree/827cea3245081923df9b0e06e5e4f33fbe7302f3/pkg/detector/library)

I'm sure the first two tasks are not difficult and good for the first contributor. There are a few things to consider when implementing it in Trivy.

**Comment by danfaizer** [comment]
Hello there,

I would like to contribute to the project and I'm thinking in implementing this feature.
You are proposing to parse `*.gemspec` but I think that the scope is slightly different than a `lock` file because it contains a range of possible compatible versions, no specific versions installed.

In example, for bundle `Gemfile.lock` you might have:
```
    parallel (1.17.0)
    parser (2.6.3.0)
      ast (~> 2.4.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
```
Is true that there are some transitive dependencies which can be version ranges, such as coderay or ast in the example above. But you know the specific version of the gem is installed:
```
 pry (0.12.2)
 parallel (1.17.0)
 parser (2.6.3.0)
```

However, in `*.gemspec` you may not have any specific version installed, just a range of compatible dependencies.
In example, this is extracted from `bitname/bitname-docker-fluentd` issue specified in this thread:
```
  gem.add_runtime_dependency("msgpack", [">= 1.3.1", "< 2.0.0"])
  gem.add_runtime_dependency("yajl-ruby", ["~> 1.0"])
  gem.add_runtime_dependency("cool.io", [">= 1.4.5", "< 2.0.0"])
  gem.add_development_dependency("oj", [">= 2.14", "< 4"])
```

Any suggestion/recommendation to proceed?
- Should I pick `{Name: msgpack Version: <2.0.0}` // no SemVer compliant
- Should I pick `{Name: msgpack Version: 2.0.0-a}` 
- Should I pick `{Name: msgpack Version: 1.3.1}`
- Other suggestion

To be honest, none of the solutions looks accurate to me. 😞

Some related documentation:
https://guides.rubygems.org/specification-reference/#add_development_dependency
https://guides.rubygems.org/patterns/#semantic-versioning
https://semvercompare.azurewebsites.net/?version=1.3.1&version=2.0.0-a&version=2.0.0

Thanks!

**Comment by knqyf263** [comment]
Thank you for looking into it, @danfaizer! We don't have to parse constraints. I was assuming that a gemspec file should have the gem's version. For example, we can know `method_source` v0.8.1 is installed in the following case.

```
root@f191f3da2db8:/# cat /usr/local/bundle/gems/method_source-0.8.2/method_source.gemspec
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "method_source"
  s.version = "0.8.1"
  ...
end
```

If we parse all gemspec files, we can get the list of installed gem names/versions.

 But I found that it might be a variable.

```
root@f191f3da2db8:/# cat /usr/local/bundle/gems/thor-0.19.4/thor.gemspec
...
Gem::Specification.new do |spec|
  ...
  spec.summary = spec.description
  spec.version = Thor::VERSION
end
```

It's a bit complex to interprets Ruby's variable. What if we use specifications?

```
root@f191f3da2db8:/# cat /usr/local/bundle/specifications/thor-0.19.4.gemspec
...
Gem::Specification.new do |s|
  s.name = "thor".freeze
  s.version = "0.19.4"
  ...
end
```

It looks like `0.19.4` is hard-coded in the gemspec. Could you consider if the way works or not? If it is still difficult, we might be able to parse a directory name such as `/usr/local/bundle/gems/thor-0.19.4`.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/1224
