### ISSUE TITLE
feat(golang): support toolchain directive

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy#7111]
## Description
Currently, when scanning Go binaries, the stdlib version is identified from the `go version -m` result, but not when scanning `go.mod`. With the introduction of [Go Toolchains](https://go.dev/doc/toolchain), the version of Go used in a project can now be strictly specified, so we should use this version as stdlib.

```
module github.com/aquasecurity/trivy

go 1.22.0

toolchain go1.22.4
```

In this example, we take `1.22.4` as the stdlib version.

**Comment by dossy** [comment]
This change mis-identifies the actual version of the toolchain used in Go programs and will result in false-positives.

See https://github.com/amacneil/dbmate/issues/665 for an example, where `go.mod` lists `go1.24.3` but the actual binary was built with `go1.24.5` as verified with `go version -m`.

The [Go Toolchains](https://go.dev/doc/toolchain) document states that the version of the toolchain that is used for building is the newer version of the installed toolchain _or_ the minimum version listed as `toolchain` in `go.mod`.

To properly identify the version used in a Go executable, you must examine the executable with `go version -m` as only inspecting `go.mod` does not guarantee what version was actually used when building the executable, leading to false-positives.

**Comment by ConProgramming** [comment]
@knqyf263 can this be reopened

**Comment by o-lee** [comment]
> [@knqyf263](https://github.com/knqyf263) can this be reopened

Or a new issue to update both the Go versions in the `go.mod`.

**Comment by DmitriyLewen** [comment]
Hello @dossy @ConProgramming @o-lee 
As we wrote in [docs](https://trivy.dev/latest/docs/coverage/language/golang/#gomod-stdlib) - Trivy doesn't check local Go version.

If your local Go version > toolchain version - Go will use local Go version.
You can check our tests in https://github.com/aquasecurity/trivy/pull/7163#discussion_r1682424315

**Comment by dossy** [comment]
This is unfortunate, because Trivy could parse the output of `go version -m` and identify the version of Go that was used to build the executable, and properly identify binaries that are built against vulnerable versions.

Reading `go.mod` tells you nothing about the contents of the actual binary that was actually built, and should not be used by vulnerability scanning tools as it will not accurately detect vulnerable executables.

Also:

https://trivy.dev/latest/docs/coverage/language/golang/#go-binary-stdlib

> Trivy detects the Go version used to compile the binary [...]

This is false.

Trivy does not detect the Go version used to compile the binary.  That requires parsing the output of `go version -m`.

It detects the minimum Go version specified in the build instructions in `go.mod`, which may be but is not necessarily the Go version that was used to compile the binary.

**Comment by DmitriyLewen** [comment]
You merge 2 different files.

> Also:
[trivy.dev/latest/docs/coverage/language/golang#go-binary-stdlib](https://trivy.dev/latest/docs/coverage/language/golang/#go-binary-stdlib)
    Trivy detects the Go version used to compile the binary [...]

This text about Go binaries. Trivy correctly detects stdlib version for Go binaries, because Go binaries contain this info.

> because Trivy could parse the output of go version -m and identify the version of Go that was used to build the executable, and properly identify binaries that are built against vulnerable versions.

from the point of view of security and usability - Trivy doesn't use third-party utilities in its work. That is why we cannot use `go version -m` command. Some users requested support for Toolchain, but since we cannot implement full functionality - we added this feature, but by default it is disabled (to enable it -  using the --detection-priority flag).

**Comment by dossy** [comment]
> from the point of view of security and usability - Trivy doesn't use third-party utilities in its work. That is why we cannot use `go version -m` command. Some users requested support for Toolchain, but since we cannot implement full functionality - we added this feature, but by default it is disabled (to enable it - using the --detection-priority flag).

If you cannot use the `go version -m` command, can you use your own Go program to inspect the binary and extract the version information?

## Code

### go-version-m.go

```go
package main

import (
	"debug/buildinfo"
	"fmt"
	"os"
)

func main() {
	f, err := os.Open(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer f.Close()

	info, err := buildinfo.Read(f)
	if err != nil {
		panic(err)
	}

	fmt.Println("Go version:", info.GoVersion)
}
```

## Example Usage

```shell
$ go run go-version-m.go dist/dbmate
Go version: go1.24.6
```

**Comment by knqyf263** [comment]
@dossy That's what we're doing today.
https://github.com/aquasecurity/trivy/blob/804ea4aa575e486fd888f59c9ceb495857b57f8c/pkg/dependency/parser/golang/binary/parse.go#L55

**Comment by dossy** [comment]
> [@dossy](https://github.com/dossy) That's what we're doing today.

@knqyf263 Then, I'm confused.  What does [`pkg/dependency/parser/golang/mod/parse.go`](https://github.com/DmitriyLewen/trivy/blob/35db88c81cc5cdb8ab25362aea455c586d2e1d32/pkg/dependency/parser/golang/mod/parse.go) do and why is it needed, if you are reading the Go stdlib version from the binary itself?

**Comment by knqyf263** [comment]
@dossy Please read https://trivy.dev/latest/docs/coverage/language/#supported-languages and https://trivy.dev/latest/docs/coverage/language/golang/
