### ISSUE TITLE
trivy do not use cached database and download it every time when start

### ISSUE THREAD

**Issue by alapierre** [aquasecurity/trivy#719]
## Description

Version: 0.12.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2020-10-21 12:21:42.374715307 +0000 UTC
  NextUpdate: 2020-10-22 00:21:42.374714307 +0000 UTC

but every time I run trivy it start downloading database again

**Comment by tisc0** [comment]
Hi,
I also have the problem now with 0.10.2, and had that problem a couple of weeks ago, with older version (0.9.2) but had no time to post since it took me a day to fix the issue in all our CI chains... for nothing since it fell back to work properly 2 days after.
Had ideas of why that would happened, and since I didn't change anything on my local binaries, the problem would have been from the server side ?

Thanks,

**Comment by mozillazg** [comment]
@alapierre @tisc0 This case is same as #675 and the root case is described in #684.

**Comment by alapierre** [comment]
today everything works fine

```
$ trivy lapierre/flyway
2020-10-25T07:35:39.023+0100	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2020-10-25T07:35:39.028+0100	INFO	Need to update DB
2020-10-25T07:35:39.028+0100	INFO	Downloading DB...
18.65 MiB / 18.65 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 7.02 MiB p/s 3s
2020-10-25T07:35:42.653+0100	INFO	Detecting Alpine vulnerabilities...

lapierre/flyway (alpine 3.12.1)
===============================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

```
trivy -v
Version: 0.12.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2020-10-25 00:43:05.269422607 +0000 UTC
  NextUpdate: 2020-10-25 12:43:05.269422107 +0000 UTC
```
```
trivy lapierre/flyway
2020-10-25T07:35:53.109+0100	WARN	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2020-10-25T07:35:53.135+0100	INFO	Detecting Alpine vulnerabilities...

lapierre/flyway (alpine 3.12.1)
===============================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by knqyf263** [comment]
@alapierre @tisc0 I'm sorry for the inconvenience. GitHub Advisory Database recently added unexpected value and Trivy DB has failed due to the change. I changed trivy-db to handle the value.

Now, @mozillazg is trying to fix the root issue (thank you, btw) and this problem won't happen again after merging his PR.
