### ISSUE TITLE
Vulnerabilities not detected by trivy

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy#840]
Hi

I have built an image which i know it contains a vulnerability (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28928) but trivy doesnt detect it

The image is javidr/alpinejdk:latest

Can you check why this issue is not being detected? I heard about problems with alpine in previous versions but im using 0.16.0

Thanks

**Comment by masahiro331** [comment]
In my environment. 
```
$ docker run --rm javidr/alpinejdk:latest /bin/bash -c "apk info musl"
musl-1.2.2-r0 description:
the musl c library (libc) implementation

musl-1.2.2-r0 webpage:
https://musl.libc.org/

musl-1.2.2-r0 installed size:
608 KiB
```

This image installed musl-1.2.2-r0.
Checking the [release note](https://musl.libc.org/releases.html), affected package is prior to 1.2.2.

Checking the  [Trivy data source](https://github.com/aquasecurity/vuln-list/blob/4451dc1571e802e73f413ad2a938abe5f5621575/alpine/3.13/main/musl.json#L10-L12) from [alpine security database](https://secdb.alpinelinux.org/v3.13/) , afflected package is 1.2.2_pre2-r0.
So I think it is correct that this vulnerability has not been detected.

I checked with the latest image, so it's possible that the image has been updated since it was reported.

**Comment by balonik** [comment]
all my alpine based images are suddenly without vulnerabilities

**Comment by knqyf263** [comment]
@javixeneize If you have any more questions, don't hesitate to reopen the issue.
