### ISSUE TITLE
Scan host images running containerd

### ISSUE THREAD

**Issue by DrissiReda** [aquasecurity/trivy#851]
I've read in the doc that if I'm running a docker container I can bind `/var/run/docker.socket` to the container, it'll detect host images. I've tried doing this with containerd instead of docker, I bound `/var/run/containerd/` (the whole folder just to be sure) and it still cannot detect containerd's local images. I don't have docker on this machine and want to use trivy with containerd, is this possible?

**Comment by knqyf263** [comment]
Trivy doesn't support the socket of containerd as of today.

**Comment by deuch** [comment]
Any plan to be compatible with containerd to check image on a host ? AKS in Azure fo to containerd with 1.19 version, so this compatibility will be a big plus !

**Comment by kaz-33** [comment]
Hello all,
no progress in this topic?
Br

**Comment by mowangdk** [comment]
I would be happy to have some guidance to take this issue. @knqyf263

**Comment by knqyf263** [comment]
Trivy depends on fanal which is a core library communicating with container runtime. Inside of fanal, it calls the API provided by container runtime. You can find two examples.
- Docker Engine
  - https://github.com/aquasecurity/fanal/blob/1b333c8c39958b5687354c9808dc28d1d90190b6/image/daemon/docker.go#L14-L53
- Podman
  - https://github.com/aquasecurity/fanal/blob/1b333c8c39958b5687354c9808dc28d1d90190b6/image/daemon/podman.go#L73-L83

What the above examples do is calling API to export a container image. Once the image is exported, the format is basically the same regardless of container runtime since it is defined as [OCI Image Spec](https://github.com/opencontainers/image-spec).

So, what we have to do is

1. Search how the containerd API works
2. Check if we can use the library of containerd to call the API like [Docker Engine](https://github.com/aquasecurity/fanal/blob/1b333c8c39958b5687354c9808dc28d1d90190b6/image/daemon/docker.go#L49)
3. If it is not the case, we may need to call the socket directly like [Podman](https://github.com/aquasecurity/fanal/blob/1b333c8c39958b5687354c9808dc28d1d90190b6/image/daemon/podman.go#L78)
4. Create a function like `func ContainerdImage(ref name.Reference) (Image, func(), error) {`
5. Call it like [this](https://github.com/aquasecurity/fanal/blob/1b333c8c39958b5687354c9808dc28d1d90190b6/image/image.go#L26-L40).

**Comment by knqyf263** [comment]
@mowangdk Please feel free to ask any questions!

**Comment by youwalther65** [comment]
Am I doing something wrong, according to docu 0.29.0 should have fixed this?!

[root@ip-10-0-1-132 containerd]# which trivy
/usr/local/bin/trivy
[root@ip-10-0-1-132 containerd]# trivy version
Version: 0.30.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-07-18 12:06:56.099185305 +0000 UTC
  NextUpdate: 2022-07-18 18:06:56.099184905 +0000 UTC
  DownloadedAt: 2022-07-18 13:56:12.228315379 +0000 UTC

[root@ip-10-0-1-132 containerd]# trivy image 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1
2022-07-18T13:57:42.638Z        INFO    Vulnerability scanning is enabled
2022-07-18T13:57:42.638Z        INFO    Secret scanning is enabled
2022-07-18T13:57:42.638Z        INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-18T13:57:42.638Z        INFO    Please see also https://aquasecurity.github.io/trivy/0.30.0/docs/secret/scanning/#recommendation for faster secret detection
2022-07-18T13:57:42.665Z        FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
        * unable to inspect the image (602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the dockerdaemon running?
        * unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
        * failed to get 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1: image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1": not found
        * GET https://602401143452.dkr.ecr.eu-west-1.amazonaws.com/v2/eks/kube-proxy/manifests/v1.22.6-minimal-eksbuild.1: unexpected status code 401 Unauthorized: Not Authorized




[root@ip-10-0-1-132 containerd]# export CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
[root@ip-10-0-1-132 containerd]# trivy image 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1
2022-07-18T14:04:16.338Z        INFO    Vulnerability scanning is enabled
2022-07-18T14:04:16.339Z        INFO    Secret scanning is enabled
2022-07-18T14:04:16.339Z        INFO    If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-07-18T14:04:16.339Z        INFO    Please see also https://aquasecurity.github.io/trivy/0.30.0/docs/secret/scanning/#recommendation for faster secret detection
2022-07-18T14:04:16.364Z        FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
        * unable to inspect the image (602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the dockerdaemon running?
        * unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
        * failed to get 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1: image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.22.6-minimal-eksbuild.1": not found
        * GET https://602401143452.dkr.ecr.eu-west-1.amazonaws.com/v2/eks/kube-proxy/manifests/v1.22.6-minimal-eksbuild.1: unexpected status code 401 Unauthorized: Not Authorized
