### ISSUE TITLE
git clone output can't be suppressed

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [aquasecurity/trivy#927]
## Description

When running `trivy repo` the progress output of the git clone operation is logged to stdout. These logs do not respect the `--quiet` flag. This interferes with automatic parsing of the results.

## What did you expect to happen?
git progress should not be logged with `--quiet`

## What happened instead?
The progress is logged to stdout.

## Output of run:

```
trivy --quiet repo github.com/aquasecurity/fanal
Enumerating objects: 968, done.
Counting objects: 100% (968/968), done.
Compressing objects: 100% (589/589), done.
Total 968 (delta 330), reused 716 (delta 199), pack-reused 0

analyzer/testdata/app/Gemfile.lock
==================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

## Output of `trivy -v`:

```
Version: 0.16.0
Vulnerability DB:
  Type: Light
  Version: 1
  UpdatedAt: 2021-03-31 12:07:53.924866843 +0000 UTC
  NextUpdate: 2021-04-01 00:07:53.924866543 +0000 UTC
  DownloadedAt: 2021-03-31 22:24:04.475611 +0000 UTC
```

**Comment by a-zen** [comment]
Hi,

I was looking into this issue but in order to fix that the fanal library needs a way to suppress the git clone output since this is happening in the library. I created the PR [335](https://github.com/aquasecurity/fanal/pull/335) for that. If that is accepted into fanal I can provide a PR to fix the issue in trivy.
