### ISSUE TITLE
Detection of unfixed vulnerabilities

### ISSUE THREAD

**Issue by gfrankliu** [aquasecurity/trivy#975]
[This table](https://aquasecurity.github.io/trivy/v0.17.1/vuln-detection/os/) has a column `Detection of unfixed vulnerabilities` which is NO for Alpine but YES for Redhat. What does that really mean? Let's say there is a vulnerability in openssl, fixed in upstream openssl, but not yet fixed the package bundled with Redhat or Alpine, will trivy only report vulnerability in Redhat but not Alpine (since unfixed yet)? Another case if upstream openssl doesn't yet have a fix, both Redhat and Alpine are waiting, will trivy only report vulnerability in Redhat but not Alpine (since unfixed yet)?

**Comment by knqyf263** [comment]
>Let's say there is a vulnerability in openssl, fixed in upstream openssl, but not yet fixed the package bundled with Redhat or Alpine, will trivy only report vulnerability in Redhat but not Alpine (since unfixed yet)?

Exactly. "Unfixed" means vulnerabilities where the patch is not provided by the vendor such as Red hat and Alpine yet regardless of the status of the upstream.

>Another case if upstream openssl doesn't yet have a fix, both Redhat and Alpine are waiting, will trivy only report vulnerability in Redhat but not Alpine (since unfixed yet)?

Right.

**Comment by gfrankliu** [comment]
Thanks! Is there a plan to bring the Alpine support on par with other OS distributions? As of now, trivy could give a false good result when it reports no vulnerability while in reality there could be one which just hasn't yet been fixed.

**Comment by gfrankliu** [comment]
https://github.com/aquasecurity/trivy/issues/474 mentioned the reason Trivy couldn't detect unfixed vulnerabilities in Alpine is because Alpine feeds don't have that information. This doesn't seem to be true anymore. eg: I can see Alpine squid 5.0.5-r0 has an unresolved CVE-2021-28116: https://security.alpinelinux.org/srcpkg/squid but Trivy scan still doesn't report that.

**Comment by kaniini** [comment]
The absence of a fix in Alpine's secdb should indicate vulnerability if a CPE rule in the NVD feed matches.

**Comment by kaniini** [comment]
With that said: due to the possibility of false positives, I wouldn't recommend that as a setting for Trivy.

It seems to me that the the way this feature is described is perhaps not helpful.

Red Hat has three states for their patch tracking: `potentially-vulnerable`, `confirmed | rejected`, `fixed`.

Alpine only has `potentially-vulnerable` and `fixed | rejected`.  The security.alpinelinux.org tracker is intended for the security team to determine whether a vulnerability needs to be fixed or rejected.

I don't see much value in a `confirmed` state, as I would rather just confirm the vulnerability by fixing it.
